# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.10"]

    runs-on: ${{matrix.os}}


    steps:
    - name: Check out repo
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        token: ${{ secrets.PAT }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        pip install seleniumbase
        pip install pytest-md-report


    - name: Test chrome with pytest
      run: |
        python -m pytest -n=4 --chrome -v --md-report --html=report_chrome.html --screenshot
        git config --global user.name 'NataliekohNP'
        git config --global user.email 'S10227870@connect.np.edu.sg'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git checkout "${GITHUB_REF:11}"
        git add -A
        git commit -am "Automated report"
        git push
      continue-on-error: true
      
    - name: Test firefox with pytest
      run: |
        seleniumbase install geckodriver
        python -m pytest -n=4 --firefox -v --md-report 
      continue-on-error: true
